# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a4dfdf71b83631dd68c0738b8010748a369f08471440cdbe2c5a527c92ef3c1ab33e8a701168419f3484f25d977cfd394129e90247190e0b6e84dad29e53451

test:
  secret_key_base: da64415482e0805196e3fdf38df5043f0c4cdd9d9b35e80504c4e02f7f95c973c95b71075e614efb842752e48a7ef0448a68f4259b37914be90bf7fd6715253b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
